name: cat_trivia
description: Flutter Developer | Test Assignment (ProArea)

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^1.4.3
  retrofit: ^3.3.1
  logger: ^1.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  cached_network_image: ^3.2.2
  flutter_bloc: ^8.1.1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.2.0
  build_runner: ^2.2.1
  json_serializable: ^6.5.0
  json_annotation: ^4.7.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
